### PR TITLE
Add support for browser lacking smooth scroll (Safari, Edge)

### PR DESCRIPTION
**Pull request by desmap**
https://github.com/frontarm/navi/issues/71

### CODE REVIEW

**Comment by jamesknelson** [comment]
Thanks for submitting this! This is definitely an improvement over the current release.

One issue is that as I understand it, some browsers silently fail instead of throwing an error when you pass in scroll options. Because of this, it may better to remove smooth scrolling from Navi altogether, with it instead handled by the user, or with scroll behavior configured somehow. Have you any thoughts on how to approach this?

**Comment by jamesknelson** [comment]
Will merge this for now. Any more significant changes can wait until the next release.

**Comment by jamesknelson** [comment]
Deployed with Navi 0.12.6

**Comment by danielnixon** [comment]
Doesn't this only fix one case and leave the other still affected? https://github.com/frontarm/navi/blob/master/packages/react-navi/src/scrollToHash.tsx#L23

**Pull request merged**
