### PR TITLE
make examples/firebase compile without warnings

### PR DESCRIPTION
**Pull request by lookfirst**
It still isn't 100%, but at least now it starts without compile warnings.

### CODE REVIEW

**Comment by jamesknelson** [comment]
Thanks for putting this together. Looks like a huge improvement on my existing example.

For what it's worth, I've also got another, newer firebase example (without auth) here:

https://github.com/jamesknelson/cura-firebase-example

**Comment by lookfirst** [comment]
Thanks @jamesknelson . You know what I'd love to see an example of is a MUI app rendering their paperbase 'premium' (it is free) theme. That's what I'm working on now. I've mostly got it working, but I'm trying to figure out how to best pass the currentUser around as well as display a different layout for logged out. I'm using your examples and have gotten pretty far (ie: it is working), but it still feels like I haven't quite figured out the best way to render everything. It really involves a lot of nested compose() and it is making my brain hurt. Ha....

**Comment by lookfirst** [comment]
@jamesknelson 

Oh man, I just had a mental / code break-through with your insanity. Excellent work with this router. Best one out there, by far!

One bit of advice? Remove the whole `{children}` example from the documentation. Make people just use `<View/>` everywhere.

Also build an example of deeply nested (2-3 layer) routes with tabs in a sub route as well as multiple layouts (one for logged in and logged out). Basically the paperbase example I mentioned above. It is a perfect example for doing a nice complex website.

**Comment by jamesknelson** [comment]
@lookfirst glad you're liking it! I'm curious to hear what the breakthrough was with your understanding?

> One bit of advice? Remove the whole {children} example from the documentation. Make people just use <View/> everywhere.

Always happy for advice on this front. Not sure which `{children}` example you mean though - could you give me a link?

> Also build an example of deeply nested (2-3 layer) routes with tabs in a sub route as well as multiple layouts (one for logged in and logged out). Basically the paperbase example I mentioned above. It is a perfect example for doing a nice complex website.

This is a great idea, although I'm pretty swamped with other work at the moment and not sure if I can find the time. If you're building something like this though, would you consider submitting a PR?

**Comment by jamesknelson** [comment]
As for `currentUser`, I usually use a separate `navigation` store and then call `setContext()` whenever the user changes. Then, instead of using `compose` to try and rope off a huge section, I'll just manually redirect for each route.

The other thing I do is wrap everything with a view that pulls in the `currentUser` from Navi context, and puts it into React context. This way, they're kept in sync and it prevents unnecessary renders when changing user.

```js

function App({ navigationContext = {} }) {
  let currentUser = navigationContext.currentUser
  let currentRoute = useCurrentRoute()
  let loadingRoute = useLoadingRoute()
  let isLoading =
    loadingRoute && loadingRoute.url.pathname !== currentRoute.url.pathname

  return (
    <CurrentUserContext.Provider value={navigationContext.currentUser}>
        <Layout
          user={currentUser}
          isLoading={isLoading}>
          <NotFoundBoundary render={renderNotFound}>
            <View />
          </NotFoundBoundary>
        </Layout>
    </CurrentUserContext.Provider>
  )
}
```

```js
export default compose(
  withView((request, context) => <App navigationContext={context} />),
  routes,
)
```

**Comment by lookfirst** [comment]
> what the breakthrough was with your understanding?

Mostly just your nomenclature is weird to me, but not the end of the world, I just have to get used to it. I think route() is what throws me off the most since I expect it to also have a path, but that is what mount() is for.

```
mount(route | compose | mount)
mount(map(() => redirect | route | mount | compose))
```

```
compose(withView(View), route | compose)
```

Seeing a visualization like the above of how all the pieces can fit together would be really helpful.

> re: `{children}`

In Layout.js:

https://frontarm.com/navi/en/guides/nested-views/

> If you're building something like this though, would you consider submitting a PR?

Also slammed busy, we will see...

> Re: your excellent code example:

In the case of this app, I don't need to worry about renders. The user is either logged in or not. If not, they see a login screen. If they are, they get the rest of the app.

The confusing part was making sure it was easy to build the 2nd level (side tab+top tab) sub navigation easily, that you can see in the paperbase example. It was tricky, but I finally got it. Might be able to get an example app up at some point.

**Comment by lookfirst** [comment]
Thank you for your comment above about the context. I totally get it now. The benefit being that I can consume that user object much further down the stack without having to pass it via properties.

I created a `SessionContext`, which is just a wrapper around my `RoutingContext`, which is just the context object I pass into the `<Router>`. I then wrapped my 'logged in' layout view with it. I now have a nice re-usable function that I can use to build any logged in body/header quite easily....

```
import React from "react";
import {RoutingContext} from "../types/RoutingContext";

export const SessionContext = React.createContext<Partial<RoutingContext>>({});

interface SessionProviderProps {
	value: RoutingContext,
	children: React.ReactNode | React.ReactNode[],
}

export const SessionProvider = ({value, children}: SessionProviderProps) => (
	<SessionContext.Provider value={value}>
		{children}
	</SessionContext.Provider>
);
```

```
export function composeMainLayoutWithHeader(aRoute: Matcher<RoutingContext>, Header: (props?: any) => JSX.Element) {
	return compose(
		withView((_, context: RoutingContext) => (
			<SessionProvider value={context}>
				<ApolloProvider client={context.apolloClient!}>
					<MainLayout/>
				</ApolloProvider>
			</SessionProvider>
		)),
		compose(
			withView((_, context: RoutingContext) => {
					return (
						<>
							<Header/>
							<MainBodyView/>
						</>
					);
				}
			),
			aRoute
		)
	);
}
```

```
export default function MainLayout({user}: MainLayoutProps) {
	const classes = useStyles();
	const [mobileOpen, setMobileOpen] = useState(false);

	const onDrawerToggle: ReactMouseEventFunc = () => {
		setMobileOpen(!mobileOpen);
	};

	return (
		<ThemeProvider theme={rootTheme}>
			<CssBaseline/>
			<div className={classes.root}>
				<nav className={classes.drawer}>
					<Hidden smUp implementation="js">
						<Navigator
							PaperProps={{style: {width: drawerWidth}}}
							variant="temporary"
							open={mobileOpen}
							onClose={onDrawerToggle}
						/>
					</Hidden>
					<Hidden xsDown implementation="css">
						<Navigator PaperProps={{style: {width: drawerWidth}}}/>
					</Hidden>
				</nav>
				<div className={classes.appContent}>
					<CommonHeader onDrawerToggle={onDrawerToggle}/>
					<View/>
				</div>
			</div>
		</ThemeProvider>
	);
}
```


```
export default route({
	getView: () => <Body/>,
	title: 'Title',
});
```

```
import {composeMainLayoutWithHeader} from "../../layout/MainLayout";
import bodyRoute from './Body';
import Header from "./Header";

export default composeMainLayoutWithHeader(bodyRoute, Header);
```

**Pull request merged**
